
MERCADO_LOCAL = 'MERCADO_LOCAL'
MERCADO_REGIONAL = 'MERCADO_REGIONAL'
MERCADO_INTERNACIONAL = 'MERCADO_INTERNACIONAL'
OTRO = 'OTRO'
COMPRA_TIPO_CHOICE = (
    (MERCADO_LOCAL, 'mercado_local'),
    (MERCADO_REGIONAL, 'mercado_regional'),
    (MERCADO_INTERNACIONAL, 'mercado_internacional'),
    (OTRO, 'otro'),

)

ORGANICA = 'ORGANICA'
JASA = 'JASA'
OTRO = 'OTRO'
CERTIFICACION_TIPO_CHOICE = (

    (ORGANICA, 'organica'),
    (JASA, 'jasa'),
    (OTRO, 'otro'),

)


QUINUA_PELADA = 'QUINUA_PELADA'
HOJUELAS = 'HOJUELAS'
HARINA = 'HARINA'
OTRO = 'OTRO'
PRODUCTO_TIPO_CHOICE = (

    (QUINUA_PELADA, 'quinua_pelada'),
    (HOJUELAS, 'hojuelas'),
    (HARINA, 'harina'),
    (OTRO, 'otro'),

)

EXPORTADOR_AGRICOLA = 'EXPORTADOR_AGRICOLA'
VINCOTOS_AGRICOLAS = 'VINCOTOS_AGRICOLAS'
SUN_PACKERS = 'SUN_PACKERS'
INTERANZA_AGRICOLA = 'INTERANZA_AGRICOLA'
APLEX_PERU = 'APLEX_PERU'
GREEN_EXPORT = 'GREEN_EXPORT'
PERU_WORLD = 'PERU_WORLD'
SERVICIO_TIPO_CHOICE = (

    (EXPORTADOR_AGRICOLA, 'exportador_agricola'),
    (VINCOTOS_AGRICOLAS, 'vincotos_agricolas'),
    (SUN_PACKERS, 'sun_packers'),
    (INTERANZA_AGRICOLA, 'interanza_agricola'),
    (APLEX_PERU, 'aplex_peru'),
    (GREEN_EXPORT, 'green_export'),
    (PERU_WORLD, 'peru_world'),


)

CONVENCIONAL = 'CONVENCIONAL'
ORGANICO = 'ORGANICO'


PRODUCCION_TIPO_CHOICE = (
    (CONVENCIONAL, 'convencional'),
    (ORGANICO, 'organico'),


)


GERENTE_ADMINISTRATIVO = 'GERENTE_ADMINISTRATIVO'
GERENTE_COMERCIAL = 'GERENTE_COMERCIAL'
GERENTE_GENERAL = 'GERENTE_GENERAL'
GERENTE_OPERACIONES = 'GERENTE_OPERACIONES'
GERENTE_PRODUCCION = 'GERENTE_PRODUCCION'
PRESIDENTE = 'PRESIDENTE'
OTROS = 'OTROS'
REPRESENTANTE_TIPO_CHOICE = (

    (GERENTE_ADMINISTRATIVO, 'gerente_administrativo'),
    (GERENTE_COMERCIAL, 'gerente_comercial'),
    (GERENTE_GENERAL, 'gerente_general'),
    (GERENTE_OPERACIONES, 'gerente_operaciones'),
    (GERENTE_PRODUCCION, 'gerente_produccion'),
    (PRESIDENTE, 'presidente'),
    (OTROS, 'otros'),


)
