# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.CharField(max_length=40)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('MERCADO_LOCAL', 'mercado_local'), ('MERCADO_REGIONAL', 'mercado_regional'), ('MERCADO_INTERNACIONAL', 'mercado_internacional'), ('OTRO', 'otro')], default='MERCADO_LOCAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'permissions': (('list_compra', 'Can list compra'), ('get_compra', 'Can get compra')),
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Compra_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoconsumo', models.CharField(max_length=40)),
                ('destino', models.CharField(max_length=40)),
                ('lugar_comercializacion', models.CharField(max_length=40)),
                ('semilla', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra_detalle',
                'permissions': (('list_compra_detalle', 'Can list compra_detalle'), ('get_compra_detalle', 'Can get compra_detalle')),
                'verbose_name_plural': 'Compra_detalles',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Compra_detalle'),
        ),
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Empresa'),
        ),
    ]
