# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico2', '0003_agroindustria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_agroindustria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('QUINUA_PELADA', 'quinua_pelada'), ('HOJUELAS', 'hojuelas'), ('HARINA', 'harina'), ('OTRO', 'otro')], default='QUINUA_PELADA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('list_producto_agroindustria', 'Can list producto_agroindustria'), ('get_producto_agroindustria', 'Can get producto_agroindustria')),
                'verbose_name_plural': 'Producto_agroindustrias',
                'verbose_name': 'Producto_agroindustria',
            },
        ),
        migrations.CreateModel(
            name='Servicio_agroindustria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('EXPORTADOR_AGRICOLA', 'exportador_agricola'), ('VINCOTOS_AGRICOLAS', 'vincotos_agricolas'), ('SUN_PACKERS', 'sun_packers'), ('INTERANZA_AGRICOLA', 'interanza_agricola'), ('APLEX_PERU', 'aplex_peru'), ('GREEN_EXPORT', 'green_export'), ('PERU_WORLD', 'peru_world')], default='EXPORTADOR_AGRICOLA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('list_servicio_agroindustria', 'Can list servicio_agroindustria'), ('get_servicio_agroindustria', 'Can get servicio_agroindustria')),
                'verbose_name_plural': 'Servicio_agroindustrias',
                'verbose_name': 'Servicio_agroindustria',
            },
        ),
        migrations.AddField(
            model_name='agroindustria',
            name='producto_agroindustria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Producto_agroindustria'),
        ),
        migrations.AddField(
            model_name='agroindustria',
            name='servicio_agroindustria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Servicio_agroindustria'),
        ),
    ]
