# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico2', '0005_auto_20170624_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_detalle',
            name='destino',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='compra_detalle',
            name='lugar_comercializacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='compra_detalle',
            name='semilla',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
