# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico2', '0006_auto_20170624_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_detalle',
            name='autoconsumo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
