# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico2', '0008_auto_20170624_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='nombre_certificadora',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
